billingsite/billingsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views
from loginapp.forms import LoginForm

urlpatterns = [
    url(r'^', include('homepageapp.urls')),
    url(r'', include('loginapp.urls')),
    url(r'login/', views.login, {'template_name':'login.html', 'authentication_form':LoginForm}, name='login'),
    # url(r'^register/', include('loginapp.urls')),
    url(r'logout/$', views.logout, {'next_page':'/login'}),
    url(r'^recipes/', include('recipes.urls')),
    url(r'^bills/', include('recipes.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billingsite/recipes/urls.py
from django.conf.urls import url
from . import views
from . import viewsRoommates

app_name = "recipes"

urlpatterns = [

# =======================================================
# ======                 Bills                     ======
# =======================================================

# ~~~~~~~~~~~ Display ~~~~~~~~~~~~

    #<WebSite.com>/bills/
    url(r'^$', views.index, name="index"),
    #<WebSite.com>/bills/
    url(r'^bymonth/$', views.indexbymonth, name="indexbymonth"),
    #<WebSite.com>/bills/<recipe_id>/
    url(r'^(?P<bill_id>[0-9]+)/$', views.viewBill, name="viewBill"),

# ~~~~~~~~~~~~~ Edit/Submit/Delete ~~~~~~~~~~~~~~~~
    #<WebSite.com>/bills/<recipe_id>/edit
    url(r'^(?P<bill_id>[0-9]+)/edit$', views.editBill, name="editBill"),

    #<WebSite.com>/bills/submit/
    url(r'^submit/$', views.submitBill, name="submitBill"),

    #<WebSite.com>/bills/<bill_id>/delete
    url(r'^(?P<bill_id>[0-9]+)/deletebill$', views.deletebill, name="deletebill"),

# =======================================================
# ======               Roommates                   ======
# =======================================================


    #<WebSite.com>/bills/
    url(r'^allroommates/$', viewsRoommates.allroommates, name="allroommates"),

    #<WebSite.com>/bills/<roommate_id>/edit
    url(r'^roommate/(?P<roommate_id>[0-9]+)/edit/$', viewsRoommates.editroommate, name="editroommate"),


    #<WebSite.com>/bills/roommate/<roommate_id>/
    url(r'^roommate/(?P<roommate_id>[0-9]+)/$', viewsRoommates.userpayments, name="userpayments"),
    #<WebSite.com>/bills/roommate/<roommate_id>/editpayment/<payment_id>/
    url(r'^roommate/(?P<roommate_id>[0-9]+)/editpayment/(?P<payment_id>[0-9]+)/$', viewsRoommates.edituserpayments, name="edituserpayments"),

    # ======================
    # ====== Payments ======
    # ======================

    # ~~~~~~~~~~~ Display ~~~~~~~~~~~~
    #<WebSite.com>/bills/
    url(r'^payments/(?P<payment_id>[0-9]+)/$', viewsRoommates.paymentdetails, name="paymentdetails"),

    # ~~~~~~~~~~~~~ Edit/Submit/Delete ~~~~~~~~~~~~~~~~
    #<WebSite.com>/bills/submitpayment/
    url(r'^submitpayment/$', viewsRoommates.submitPayment, name="submitPayment"),
    #<WebSite.com>/bills/submitPaymentFor/
    url(r'^submitpaymentfor/(?P<roommate_id>[0-9]+)$', viewsRoommates.submitPaymentFor, name="submitPaymentFor"),

    #<WebSite.com>/bills/<bill_id>/delete
    url(r'^(?P<payment_id>[0-9]+)/deletepayment$', viewsRoommates.deletepayment, name="deletepayment"),

]

billingsite/recipes/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.
class Bills(models.Model):
    PGE = 'PG&E'
    WATER = "CalWater"
    COMCAST = "Comcast"
    BILL_CHOICES = (
        (PGE, 'PG&E'),
        (WATER, 'CalWater'),
        (COMCAST, 'Comcast'),
    )
    category = models.CharField(max_length=8, choices=BILL_CHOICES)
    description = models.CharField(max_length=200, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    dateissued = models.DateField(null=True, blank=True)
    image = models.FileField(max_length=144, upload_to='uploads/%Y/%m/%d/', null=True, blank=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    priceper = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    amount = models.DecimalField(max_digits=5, decimal_places=2)
    month = models.ForeignKey('BillingMonth', null=True, blank=True, default="", on_delete=models.SET_DEFAULT, db_constraint=False)



    def __str__(self):
        Bills.objects.order_by('-self.date')
        return str(self.id) + " - " + str(self.category) + " - " + self.month.themonth + " - $" + str(self.amount)
    def save(self, *args, **kwargs):
        all_bills = Bills.objects.all()
        if Bills.objects.filter(month=self.month, category=self.category).exists():
            bill = Bills.objects.get(month=self.month, category=self.category)
            if str(bill.id) == str(self.id):
                print("same bill, update it")
            else:
                raise ValidationError("This Bill Already Exists")
        if self.priceper:
            self.priceper = self.amount/5
        super(Bills, self).save(*args, **kwargs)

class BillingMonth(models.Model):
    class Meta:
        ordering = ('-theyear', '-themonthnum')
    jan = "January"; feb = "February"; mar = "March"; apr = "April";
    may = "May"; jun = "June"; jul = "July"; aug = "August";
    sept= "September"; octo= "October"; nov = "November"; dec = "December";
    MONTH_CHOICES = (
        (jan, 'January'), (feb, 'February'), (mar, 'March'),(apr, 'April'), (may, 'May'),
        (jun, 'June'), (jul, 'July'), (aug, 'August'), (sept, 'September'),
        (octo, 'October'), (nov, 'November'), (dec, 'December'),
    )

    year_range = range(2014, 2020, 1);
    YEAR_CHOICES = ( (i, i) for i in year_range )
    # themonth = models.DateField()
    themonth = models.CharField(max_length=12, choices=MONTH_CHOICES)
    themonthnum = models.IntegerField(default="", null=True, blank=True)
    theyear = models.IntegerField(choices=YEAR_CHOICES, default="")
    priceperroomate = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True, default=0)
    pgebill = models.ForeignKey('Bills', null=True, blank=True, default="", on_delete=models.SET_DEFAULT, related_name="thepgebill", db_constraint=False)
    calwaterbill = models.ForeignKey('Bills', null=True, blank=True, default="", on_delete=models.SET_DEFAULT, related_name="thewaterbill", db_constraint=False)
    comcastbill = models.ForeignKey('Bills', null=True, blank=True, default="", on_delete=models.SET_DEFAULT, related_name="thecomcastbill", db_constraint=False)

    def save(self, *args, **kwargs):
        if self.themonth == "January": self.themonthnum = 1
        elif self.themonth == "February": self.themonthnum = 2
        elif self.themonth == "March": self.themonthnum = 3
        elif self.themonth == "April": self.themonthnum = 4
        elif self.themonth == "May": self.themonthnum = 5
        elif self.themonth == "June": self.themonthnum = 6
        elif self.themonth == "July": self.themonthnum = 7
        elif self.themonth == "August": self.themonthnum = 8
        elif self.themonth == "September": self.themonthnum = 9
        elif self.themonth == "October": self.themonthnum = 10
        elif self.themonth == "November": self.themonthnum = 11
        elif self.themonth == "December": self.themonthnum = 12
        super(BillingMonth, self).save(*args, **kwargs)

    def __str__(self):
        BillingMonth.objects.all().order_by('-theyear').order_by('-themonthnum')
        # return (str(self.themonth.strftime('%b %Y')))
        pge = ""
        water = ""
        comcast = ""
        if self.pgebill:
            pge = str("$" + str(self.pgebill.amount))
        else:
            pge = "$ 0.00"
        if self.calwaterbill:
            water = str("$" + str(self.calwaterbill.amount))
        else:
            water = "$ 0.00"
        if self.comcastbill:
            comcast = str("$" + str(self.comcastbill))
        else:
            comcast = "$ 0.00"
        return str(self.theyear) + " - " + str(self.themonth) + ' - PG&E: '+ pge + ' - CalWater: ' + water + ' - Comcast: ' + comcast

    def addbill(self, instance, cat, *args, **kwargs):
        total = self.priceperroomate
        total = 0
        if cat == "none":
            print("Bill was deleted, recalculating Price Per Roommate")
        else:
            if cat == "PG&E":
                self.pgebill = Bills.objects.get(pk=instance)
            if cat == "CalWater":
                self.calwaterbill = Bills.objects.get(pk=instance)
            if cat == "Comcast":
                self.comcastbill = Bills.objects.get(pk=instance)
        if self.pgebill:
            total = total + self.pgebill.amount
        if self.calwaterbill:
            total = total + self.calwaterbill.amount
        if self.comcastbill:
            total = total + self.comcastbill.amount
        if total == 0:
            self.priceperroomate = 0
        else:
            total = total / 5
            self.priceperroomate = total
        if self.themonth == "January": self.themonthnum = 1
        elif self.themonth == "February": self.themonthnum = 2
        elif self.themonth == "March": self.themonthnum = 3
        elif self.themonth == "April": self.themonthnum = 4
        elif self.themonth == "May": self.themonthnum = 5
        elif self.themonth == "June": self.themonthnum = 6
        elif self.themonth == "July": self.themonthnum = 7
        elif self.themonth == "August": self.themonthnum = 8
        elif self.themonth == "September": self.themonthnum = 9
        elif self.themonth == "October": self.themonthnum = 10
        elif self.themonth == "November": self.themonthnum = 11
        elif self.themonth == "December": self.themonthnum = 12
        print("Added/deleted Payment, new Price_Per_Rommate: $" + str(self.priceperroomate))
        super(BillingMonth, self).save(*args, **kwargs)
    def new(self, *args, **kwargs):
        if self.themonth == "January": self.themonthnum = 1
        elif self.themonth == "February": self.themonthnum = 2
        elif self.themonth == "March": self.themonthnum = 3
        elif self.themonth == "April": self.themonthnum = 4
        elif self.themonth == "May": self.themonthnum = 5
        elif self.themonth == "June": self.themonthnum = 6
        elif self.themonth == "July": self.themonthnum = 7
        elif self.themonth == "August": self.themonthnum = 8
        elif self.themonth == "September": self.themonthnum = 9
        elif self.themonth == "October": self.themonthnum = 10
        elif self.themonth == "November": self.themonthnum = 11
        elif self.themonth == "December": self.themonthnum = 12
        print(self.themonth)
        super(BillingMonth, self).save(*args, **kwargs)

billingsite/recipes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.html import escape
from django.http import JsonResponse
import datetime
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.db.models import Q

import json as json
from .forms import RecipeForm, MonthForm
from .models import Bills, BillingMonth
from loginapp.models import Payments, Roommates, homeMOTD
from loginapp.forms import PaymentForm, RoommatesForm

# Create your views here.

# ===========================
# ======  Display ===========
# ===========================

# All Bills listed by date submitted
@login_required(login_url="/login/")
def index(request):
    all_bills = Bills.objects.all().order_by('-date')
    context = {
        'sitename':"RoomateBills",
        'page_name':"Bills",
        'all_bills':all_bills,
    }
    return render(request, 'bills.html', context)

# All Bills Organized by Month
@login_required(login_url="/login/")
def indexbymonth(request):
    month_bills = BillingMonth.objects.all()
    month_bills = month_bills.order_by('-theyear', '-themonthnum')
    web_info    = homeMOTD.objects.get(pk=1)
    all_roommates = Roommates.objects.all()
    context = {
        'sitename':"RoomateBills",
        'page_name':"Bills",
        'month_bills':month_bills,
        'web_info':web_info,
    }
    return render(request, 'billsbymonth.html', context)

# Details of a single Bill
@login_required(login_url="/login/")
def viewBill(request, bill_id):
    bill = Bills.objects.get(pk=bill_id)
    month = bill.month
    context = {
        'bill':bill,
        'month':month,
    }
    return render(request, 'billdetails.html', context)

# ===========================
# ===== Create/Submit  ======
# ===========================

@login_required(login_url="/login/")
def submitBill(request):
    if request.method=='POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            j = form.save(request, commit=False)
            j.save()
            BillingMonth.objects.get(pk=j.month.id).addbill(instance=j.id, cat=j.category)
            return HttpResponseRedirect('/bills/bymonth')
    else:
        form = RecipeForm()
    context = {
        'sitename':"EdgarRaw",
        'page_name':"Add a Bill - EdgarRaw",
        'form':form,
    }
    return render(request, 'addbill.html', context)

# ===========================
# ========  Edit  ===========
# ===========================

@login_required(login_url="/login/")
def editBill(request, bill_id):
    post = Bills.objects.get(pk=bill_id)
    thefile = post.image
    if request.method == "POST":
        form = RecipeForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.update(instance=bill_id, thefile=thefile, commit=False)
            post.save()
            context = {
                'bill':post,
            }
            return render(request, 'billDetails.html', context)
    else:
        form = RecipeForm(instance=post)
    context = {
        'post':post,
        'form':form,
    }
    return render(request, 'editbill.html', context)

# ===========================
# ======== Delete ===========
# ===========================

@login_required(login_url="/login/")
def deletebill(request, bill_id):
    bill = Bills.objects.get(pk=bill_id)
    month = bill.month.id
    bill.delete()
    BillingMonth.objects.get(pk=bill.month.id).addbill(instance=0, cat="none")
    return HttpResponseRedirect("/bills/")

billingsite/recipes/templates/addbill.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ page_name }} {% endblock title %}
{% block content %}
<div class="column">
  <div class="medium-12 medium-centered large-8 large-centered row">
    <!-- <form method="post" action="/bills/submit"> -->
    {% if user.is_superuser %}
                      {# enctype as seen here \/ is required for handling ImageField and FileFields #}
    <form method="post" action="" enctype="multipart/form-data" runat="server">
      {% csrf_token %}
        <h1 class="text-center">Add a new Bill</h1>
        {{ form.errors }}
        <div class="large-6 medium-6 small-6 column">
          <label> {{ form.category.label_tag }}
            {{ form.category }}
          </label>
        </div>
        <div class="large-6 medium-6 small-6 column">
          <label> {{ form.month.label_tag }}
            {{ form.month }}
          </label>
        </div>
        <div class="large-3 medium-4 small-6 column">
          <label>
            {{ form.amount.label_tag }}
            {{ form.amount }}
          </label>
        </div>
        <div class="large-3 medium-4 small-6 column">
          <label> {{ form.date.label_tag }}
            {{ form.date }}
          </label>
        </div>
        <div class="large-3 medium-4 small-6 column">
          <label> {{ form.dateissued.label_tag }}
            {{ form.dateissued }}
          </label>
        </div>
        <div class="large-3 medium-4 small-6 column">
          <label> {{ form.image.label_tag }}
            {{ form.image }}
          </label>
        </div>
        <div class="large-12 column">
          <label> {{ form.description.label_tag }}
            {{ form.description }}
          </label>
        </div>
        <input type="submit" class="button expanded" value="Submit Bill">
    </form>
    <form action="/bills/bymonth">
        <input type="submit" class="button expanded alert" value="Cancel">
    </form>
    {% else %}
    <h1>You must be logged into an admin account to add a recipe... Nice try Bub</h1>
    {% endif %}
  </div>
</div>
{% endblock %}

billingsite/recipes/templates/addpayment.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ page_name }} {% endblock title %}
{% block content %}
<div class="row">
  <div class="medium-6 medium-centered large-8 large-centered columns">
    <!-- <form method="post" action="/bills/submit"> -->
    {% if user.is_superuser %}
                      {# enctype as seen here \/ is required for handling ImageField and FileFields #}
    <form method="post" action="" enctype="multipart/form-data" runat="server">
      {% csrf_token %}
      <div class="row column">
        <h1 class="text-center">Add a new Bill</h1>
        {{ form.errors }}
        <label> {{ form.roommate.label_tag }}
          {{ form.roommate }}
        </label>
        <label> {{ form.paymenttype.label_tag }}
          {{ form.paymenttype }}
        </label>
        <label> {{ form.amount.label_tag }}
          {{ form.amount }}
        </label>
        <label> {{ form.description.label_tag }}
          {{ form.description }}
        </label>
        <label> {{ form.datepaid.label_tag }}
          {{ form.datepaid }}
        </label>
        <input type="submit" class="button expanded" value="Submit Payment">
      </div>
    </form>
    <form action="/bills/">
        <input type="submit" class="button expanded alert" value="Cancel">
    </form>
    {% else %}
    <h1>You must be logged into an admin account to add a recipe... Nice try Bub</h1>
    {% endif %}
  </div>
</div>
{% endblock %}

billingsite/recipes/templates/allroommates.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ page_name }} {% endblock title %}
{% block content %}
<h1><center>Roommate Payments</center></h1>
<div class="row small-8 medium-8 large-8">
    <form method="post" action="/bills/search">
      {% csrf_token %}
        <input type="text" name="term" size="30" placeholder="Search for a Roomate/Bill..."/>
        <input type="submit" class="button expanded" value="Search" />
    </form>
</div>
<div class="row small-12 small-centered medium-12 medium-centered large-3 large-centered">
  <div class="column">
    <table class="striped">
      <thead>
        <tr>
          <th width="20" id="TOTALS"><b>TOTALS</b></th>
          <th id="owed"> Owed </th>
          <th id="paid"> Paid </th>
          <th id="stillowed"> Left </th>
        </tr>
      </thead>
      {% for person in roommates %}
      <tbody>
        <tr id="userTotals">
          {% if person.name == "Edgar" %}
            <td id="Edgar"> {{person.name}} </td>
          {% elif person.name == "Mike" %}
            <td id="Mike"> {{person.name}} </td>
          {% elif person.name == "Marc" %}
            <td id="Marc"> {{person.name}} </td>
          {% elif person.name == "Erik" %}
            <td id="Erik"> {{person.name}} </td>
          {% elif person.name == "John" %}
            <td id="John"> {{person.name}} </td>
          {% elif person.name == "Johnny" %}
            <td id="Johnny"> {{person.name}} </td>
          {% elif person.name == "Dom" %}
            <td id="Dom"> {{person.name}} </td>
          {% else %}
            <td id="Johnny"> {{person.name}} </td>
          {% endif %}
          <td pos="centered" id="owed"> ${{person.totalowed}}</td>
          <td id="paid"> ${{person.totalpaid}}</td>
          {% if person.stillowed <= 0 %}
            <td id="stillowed0"> ${{person.stillowed}}</td>
          {% elif person.stillowed <= 30 %}
            <td id="stillowed25"> ${{person.stillowed}}</td>
          {% elif person.stillowed <= 60 %}
            <td id="stillowed50"> ${{person.stillowed}}</td>
          {% elif person.stillowed <= 140 %}
            <td id="stillowed75"> ${{person.stillowed}}</td>
          {% elif person.stillowed <= 200 %}
            <td id="stillowed100"> ${{person.stillowed}}</td>
          {% elif person.stillowed > 200 %}
            <td id="stillowed100"> ${{person.stillowed}}</td>
          {% else %}
          {% endif %}
        </tr>
      </tbody>
      {% endfor %}
    </table>
  </div>
</div>
<div class="row small-up-1 medium-up-1 large-up-2">
  {% if roommates %}
  {% for person in roommates %}
    <div class="column">
      {% csrf_token %}
      <h2><a href="/bills/roommate/{{ person.id }}/">Payments for {{ person.name }}</a></h2>
      <table class="hover">
        <thead>
          <tr>
            <th width="100"> Amount </th>
            <th witdh="50">Type</th>
            <th>Details</th>
            <th width="100">Date Paid</th>
            <th width="100">Total Still Owed</th>
          </tr>
        </thead>
        {% if payments %}
        {% for item in payments %}
        <tbody>
          <tr class="hover">
            {% if item.roommate == person %}
              {% if item.amount %}
              <td> <a href="/bills/payments/{{ item.id }}/">{{ item.amount }}</a></td>
              {% else %}
              <td><a href="/bills/payments/{{ item.id }}/">---</a></td>
              {% endif %}
              {% if item.paymenttype %}
              <td> <a href="/bills/payments/{{ item.id }}/">{{ item.paymenttype }}</a></td>
              {% else %}
              <td><a href="/bills/payments/{{ item.id }}/">---</a></td>
              {% endif %}
              {% if item.description %}
              <td> <a href="/bills/payments/{{ item.id }}/">{{ item.description }}</a></td>
              {% else %}
              <td><a href="/bills/payments/{{ item.id }}/">---</a></td>
              {% endif %}
              {% if item.datepaid %}
              <td> <a href="/bills/payments/{{ item.id }}/">{{ item.datepaid }}</a></td>
              {% else %}
              <td><a href="/bills/payments/{{ item.id }}/">---</a></td>
              {% endif %}
              <td><a href="/bills/payments/{{ item.id }}/">---</a></td>
            {% endif %}
          </tr>
        </tbody>
        {% endfor %}
        {% endif %}
          <tr>
            <td>
              Total Paid:
            </td>
            <td>${{ person.totalpaid }}</td>
            <td> </td>
            <td> </td>
            <td>${{ person.stillowed }} </td>
          </tr>
      </table>
    </div>
  {% endfor %}
  {% else %}
    <h3>You have not uploaded any Recipes yet.</h3>
    <h3><a href="/bills/submit">Click Here</a> to upload a new recipe</h3>
  {% endif %}
</div>
{% endblock %}

billingsite/recipes/templates/billDetails.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ page_name }} {% endblock title %}

{% block content %}

<div class="large-7 large-centered medium-3 columns">
  {% if user.is_superuser %}
  <h2>{{ bill.category }} for {{ bill.date | date:'F Y'}}</h2>
  <br />
  <div class="large-11 medium-11 small-12 text-center">
      {# EDIT button, to edit recipe #}
      <a role="button" href="/bills/{{ bill.id }}/edit" class="button"><font size="4">Edit Bill</font></a>
      {# DELETE button that opens a Modal to confirm#}
      <a data-open="deleteRecipe" role="button" class="button alert">DELETE BILL</a>
      {# The CONFIRM DELETE Modal #}
      <div class="reveal" id="deleteRecipe" data-reveal>
        <h1 class="text-center">WARNING!</h1>
        <h3 class="text-center">Are you sure you wish to delete:</h3>
        <h3 class="text-center">{{ bill.category }}</h3>
        <a role="button" href="/bills/{{ bill.id }}/deletebill" class="button expanded large alert">DELETE</a>
        <button class="close-button" data-close aria-label="Close modal" type="button">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
  </div>
  {% else %}
  {% endif %}
  {% if bill %}
  <table>
    <thead>
      <tr>
        <th width="500"> Bill Category </th>
        <th width="200"> Price </th>
        <th width="200"> Per Roomate </th>
        <th width="300"> Month </th>
        <th width="200">Due Date</th>
        <th width="200">Statement Date</th>
        <th width="500"> PDF Download </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> {{ bill.category }} </td>
        <td> $ {{ bill.amount }} </td>
        <td> $ {{ bill.priceper }} </td>
        <td> <a href="/bills/bymonth/{{ bill.month.id }}">{{ bill.month.themonth }} - {{ bill.month.theyear }}</a></td>
        <td> {{ bill.date}} </td>
        <td> {{ bill.dateissued}} </td>
        <td> <a href="/media/{{ bill.image }}" download="media/{{ bill.image }}">{{ bill.category }} PDF</a> </td>
      </tr>
    </tbody>
  </table>
  {# Go back button #}
  <a role="button" href="/bills/bymonth" class="success button expanded"><font size="4">Go back to Bills</font></a>
  {% else %}
  <h3>You have not uploaded any bills yet.</h3>
  <h3><a href="/bills/submit">Click Here</a> to upload a new bill</h3>
  {% endif %}
{% endblock %}

billingsite/recipes/templates/editrecipe.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ page_name }} {% endblock title %}
{% block content %}
<div class="row">
  <div class="medium-6 medium-centered large-8 large-centered columns">
    <!-- <form method="post" action="/bills/submit"> -->
    {% if user.is_superuser %}
    <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row column">
        <h1 class="text-center">Edit recipe</h1>
        {{ form.errors }}
        <h3 class="text-left">Editting: {{ post.title }}</h3>
        <label> {{ form.title.label_tag }}
          {{ form.title }}
        </label>
        <label> {{ form.description.label_tag }}
          {{ form.description }}
        </label>
        <label> {{ form.ingredients.label_tag }}
          {{ form.ingredients }}
        </label>
        <label> {{ form.recipe.label_tag }}
          {{ form.recipe }}
        </label>

        {# had to manually enter form.image information as to add "onchange=" attr for JS preview #}
        <tr>
          <th>
            <div class="large-12 medium-12 medium-centered small-12 small-centered row">
              <div class="large-6 large-left medium-5 medium-left columns"> <br />
                <label for="id_image">Current Image: <br />{{ post.image.name }}</label>
                <img class="" src="{{ post.image.url }}" alt="" width=400 height=400>
              </div>
              <div class="large-6 large-right medium-5 medium-right columns"> <br />
                {# The Preview Image #}
                <font size="3">
                  New Image Preview:<br /><br />
                </font>
                <img class="" id="output" src="#" alt="Please select an image to upload..." height="400" width="400"/><br /><br />
              </div>
            </div>
          </th>
            <p>
              Replace Image:
            </p>
          <td>
            <input id="id_image" name="image" type="file" onchange="loadFile(event)"required />
          </td>
        </tr>
        {# JS to provide an Image Preview when uploading a new image #}
        <script>
          var loadFile = function(event) {
            var output = document.getElementById('output');
            output.src = URL.createObjectURL(event.target.files[0]);
          };
        </script>

        <input type="submit" class="button expanded" value="Confirm Edit">
      </div>
    </form>
        <a role="button" href="/bills/{{ post.id }}" class="button alert expanded">Cancel</a>

    {% else %}
    <h1>You must be logged into an admin account to edit recipes... Nice try Bub</h1>
    {% endif %}
  </div>
</div>
{% endblock %}